name="harshitH!!!!!!1234"
#uppper
print(name.upper())
#lower
print(name.lower())
#rstrip
print(name.rstrip("34"))
#replace
print(name.replace("hars","harry"))
#split
print(name.split("h"))
#capitalize
print(name.capitalize())
#center alignment
print(name.center(50))
#count
print(name.count("h"))
#endswith
print(name.endswith("h"))
#find
print(name.find("ha"))
#index
print(name.index("ha"))
#isalnum
print(name.isalnum())
#isalpha
print(name.isalpha())
#islower
print(name.islower())
#isprintable
print(name.isprintable())
#isspace
print(name.isspace())
#istitle
print(name.istitle())
#isupper
print(name.isupper())
#startswith
print(name.startswith("ha"))
#swapcase
print(name.swapcase())
#title
print(name.title())
#

